### ISSUE TITLE
philox uses wrong indices

### ISSUE THREAD

**Issue by fabienlefloch** [xayon40-12/gpgpu-rs#2]
Compared to the reference code in C, philox.rs uses wrong indices in each round:
counter[0] = hi1^key[1]^counter[3];
vs
hi1 ^ ctr.v[1] ^ key.v[0],

**Comment by xayon40-12** [comment]
By wrong indices do you mean I forgot to permute the counters?

currently I have 
```rust
        counter[0] = hi1^key[1]^counter[3];
        counter[2] = hi0^key[0]^counter[1];
        counter[1] = lo0;
        counter[3] = lo1;
```

And looking at the source code from random123 I think I should have permuted the indices of counter at the left if "=" which would produce:

```rust
        counter[0] = hi0^key[0]^counter[1];
        counter[1] = lo1;
        counter[2] = hi1^key[1]^counter[3];
        counter[3] = lo0;
```

I used the paper from random123 to write philox.rs (so I might have forgotten the permutation step). The only reference code I know is
https://www.thesalmons.org/john/random123/releases/1.00/docs/philox_8h_source.html
but it is difficult to read.
Do you have another reference?

**Comment by fabienlefloch** [comment]
Yes, this is it. I looked at V1.09 tar.gz file from the website:

```
R123_CUDA_DEVICE R123_STATIC_INLINE R123_FORCE_INLINE(struct r123array4x##W _philox4x##W##round(struct r123array4x##W ctr, struct r123array2x##W key)); \
R123_CUDA_DEVICE R123_STATIC_INLINE struct r123array4x##W _philox4x##W##round(struct r123array4x##W ctr, struct r123array2x##W key){ \
    T hi0;                                                              \
    T hi1;                                                              \
    T lo0 = mulhilo##W(PHILOX_M4x##W##_0, ctr.v[0], &hi0);              \
    T lo1 = mulhilo##W(PHILOX_M4x##W##_1, ctr.v[2], &hi1);              \
    struct r123array4x##W out = {{hi1^ctr.v[1]^key.v[0], lo1,               \
                              hi0^ctr.v[3]^key.v[1], lo0}};             \
    return out;                                                         \
}
```

**Comment by xayon40-12** [comment]
Thank you very much for noticing this mistake. It is now updated (as well as the gpu counterpart, with a new test in test.rs to compare both implementations).
